### ISSUE TITLE
SQL error when running #counter_culture_fix_counts

### ISSUE THREAD

**Issue by trostli** [magnusvk/counter_culture#113]
Hi there,

I am getting the following error when running counter_culture_fix_counts, however it only happens midway through processing close to 1 million records. Any chance you know what the issue might be?

Thanks very much!

```
  User Load (2437.0ms)  SELECT  users.id, users.id, COUNT(performances.id) AS count, users.performances_count FROM "users" LEFT JOIN performances AS performances ON users.id = performances.user_id AND (performances.published_at IS NOT NULL) WHERE "users"."deleted_at" IS NULL GROUP BY "users"."id"  ORDER BY "users"."id" ASC LIMIT 1000 OFFSET 1021000
  User Load (6.5ms)  SELECT  users.id, users.id, COUNT(performances.id) AS count, users. FROM "users" LEFT JOIN performances AS performances ON users.id = performances.user_id AND (performances.published_at IS NULL) WHERE "users"."deleted_at" IS NULL GROUP BY "users"."id"  ORDER BY "users"."id" ASC LIMIT 1000 OFFSET 0
PG::SyntaxError: ERROR:  syntax error at or near "LEFT"
LINE 1: ...NT(performances.id) AS count, users. FROM "users" LEFT JOIN ...
                                                             ^
: SELECT  users.id, users.id, COUNT(performances.id) AS count, users. FROM "users" LEFT JOIN performances AS performances ON users.id = performances.user_id AND (performances.published_at IS NULL) WHERE "users"."deleted_at" IS NULL GROUP BY "users"."id"  ORDER BY "users"."id" ASC LIMIT 1000 OFFSET 0
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "LEFT"
LINE 1: ...NT(performances.id) AS count, users. FROM "users" LEFT JOIN ...
                                                             ^
: SELECT  users.id, users.id, COUNT(performances.id) AS count, users. FROM "users" LEFT JOIN performances AS performances ON users.id = performances.user_id AND (performances.published_at IS NULL) WHERE "users"."deleted_at" IS NULL GROUP BY "users"."id"  ORDER BY "users"."id" ASC LIMIT 1000 OFFSET 0
	from /Users/daniel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
	from /Users/daniel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
```

**Comment by magnusvk** [comment]
It's missing the column name in that last query (`performances_count`). Are you using dynamic names here or something? This is hard to debug without a full failing test or at least some more info on how you've set up the counter caches. Feel free to reopen with more info.
