### ISSUE TITLE
Possible to update counts when attribute changes on model

### ISSUE THREAD

**Issue by danielbonnell** [magnusvk/counter_culture#189]
I've got the following in my `Request` model:

```
class Request < ApplicationRecord
    belongs_to :contact
    counter_culture :contact, touch: true
    counter_culture :contact,
        column_name: Proc.new {|cp| cp.read ? 'completed_requests_count' : nil },
        column_names: {
            ["requests.completed = ?", true] => 'completed_requests_count'
        },
        touch: true
end

```
I know that when I create a new instance of `Request` that the `requests_count` field on my `Contact` model will be updated. What I would like to know is if it's possible to update the `completed_requests_count` field on `Contact` when an existing (already committed) instance of `Request` is updated such that `request.complete = true`. Currently this counter cache and others (I have dozens of conditional counter caches like this on many different models) do not automatically update when a change is committed to an instance of `Request`. I get around this by scheduling `Request.counter_culture_fix_counts` to run periodically in a background job, however this is not very performant especially when I have to do this for a lot of different models and frequently.

**Comment by magnusvk** [comment]
This should work correctly. [There's a test for exactly the behavior you are describing](https://github.com/magnusvk/counter_culture/blob/master/spec/counter_culture_spec.rb#L426) so I'm pretty sure this works.

Without seeing more context here I can't tell why this isn't working for you. Two guesses would be that you're changing the value without callbacks (thus preventing counter_culture from noticing) or that the `cp.read` method doesn't correspond to the `completed` column.

**Comment by danielbonnell** [comment]
I'm just using the standard approach to update the request: `request.update(completed: true)`, which should trigger the callbacks on that model. I know for example that if I feed in invalid values for other attributes that the validations will fail, so not sure why the counter_culture callbacks would not be firing.

**Comment by magnusvk** [comment]
@danielbonnell in the `column_name` `Proc`, why doesn't it read `cp.completed?` instead of `cp.read`? Also, I have a test for this specifically. That's a very strong indication that the problem lies in your code here. I'd be happy to reconsider that opinion if you could provide a failing test case in a PR.

**Comment by danielbonnell** [comment]
@magnusvk I see, you are right, it is my code. Changing it to `cp.completed` worked perfectly. Maybe I'm just not understanding the docs correctly then, but it looks like in my example, I don't actually need the `column_names` argument just the `column_name` argument with `cp.completed` or whatever other attribute I'm checking against, right?

**Comment by magnusvk** [comment]
If you remove `column_names` then `counter_culture_fix_counts` will stop working. This is all documented: https://github.com/magnusvk/counter_culture#handling-dynamic-column-names

**Comment by danielricecodes** [comment]
@magnusvk - could you explain this a little bit more?  

> the `cp.read` method doesn't correspond to the completed column.

I'm having a similar issue with this gem, albeit I am trying it out and my scenario is much more complex than anything I've seen others post.  Essentially, I'm noticing that my conditional counter cache is being ignored when I update a record.  When I create the record, the counter is updated as expected.

I'm trying to use your gem to keep various prize pool counters up to date.  There are 9 prize pool columns on the Contest Model, one delta-type counter column for each "wager_type".  I only want to add/subtract from the counter if the Wager's status is Approved, Loss, or Win.  

I'd really appreciate your help.  Am I pushing the gem's limits here?  I wrote RSpec tests that highlight the issue I'm having also.  All the "on create" tests pass.  The "on update" tests fail.  One test, updating from 'pending' to 'rejected' actually reduces the counter - which IS NOT what I was expecting should happen.

Relevant code is below and THANK YOU IN ADVANCE

#### Model (with bits redacted)

```ruby
class Wager < ApplicationRecord

  belongs_to :user
  belongs_to :contest

  counter_culture :contest,
    delta_column: 'amount_cents',
    column_name: proc { |model| model.approved? || model.win? || model.loss? ? "#{model.wager_type}_pool_cents" : nil },
    column_names: {
      ["#{self.quoted_table_name}.wager_type = ?", 'WIN'] => 'win_bet_pool_cents',
      ["#{self.quoted_table_name}.wager_type = ?", 'PLC'] => 'place_bet_pool_cents',
      ["#{self.quoted_table_name}.wager_type = ?", 'SHW'] => 'show_bet_pool_cents',
      ["#{self.quoted_table_name}.wager_type = ?", 'EXA'] => 'exacta_pool_cents',
      ["#{self.quoted_table_name}.wager_type = ?", 'QNL'] => 'exacta_box_pool_cents',
      ["#{self.quoted_table_name}.wager_type = ?", 'TRI'] => 'trifecta_pool_cents',
      ["#{self.quoted_table_name}.wager_type = ?", 'TRO'] => 'trifecta_box_pool_cents',
      ["#{self.quoted_table_name}.wager_type = ?", 'SFC'] => 'superfecta_pool_cents',
      ["#{self.quoted_table_name}.wager_type = ?", 'FF4'] => 'superfecta_box_pool_cents',
    }

  enum status: { pending: 0, approved: 1, rejected: 2, win: 3, loss: 4 }
  
  enum wager_type: { 
    win_bet:        'WIN', # 1/
    place_bet:      'PLC', # 1/
    show_bet:       'SHW', # 1/
    exacta:         'EXA', # 1/2/
    exacta_box:     'QNL', # 1/2/
    trifecta:       'TRI', # 1/2/3/
    trifecta_box:   'TRO', # 1/2/3/ => 1,2,3///
    superfecta:     'SFC', # 1/2/3/4/
    superfecta_box: 'FF4', # 1/2/3/4/ => 1,2,3,4////
  }
end

class Contest < ApplicationRecord
  has_many :wagers
end
```

#### RSPec tests
```
require 'rails_helper'

RSpec.describe Wager, type: :model do
describe "prize pool counter caches" do
    
    let!(:contest) { create(:contest) }
    
    before do
      allow_any_instance_of(Wager).to receive(:valid_teams_string?).and_return(true)
    end
    
    context "when creating a new wager" do
      it "does not add to the pool when pending" do
        expect {
          create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :pending, contest: contest, amount: 100.to_money)
        }.to_not change {
          contest.reload.win_bet_pool
        }
      end
      it "does not add to the pool when rejected" do
        expect {
          create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :rejected, contest: contest, amount: 100.to_money)
        }.to_not change {
          contest.reload.win_bet_pool
        }
      end
      it "does add to the pool when loss" do
        expect {
          create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :loss, contest: contest, amount: 100.to_money)
        }.to change {
          contest.reload.win_bet_pool
        }.from(Money.zero).to(100.to_money)
      end
      it "does add to the pool when approved" do
        expect {
          create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :approved, contest: contest, amount: 100.to_money)
        }.to change {
          contest.reload.win_bet_pool
        }.from(Money.zero).to(100.to_money)
      end
      it "does add to the pool when win" do
        expect {
          create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :win, contest: contest, amount: 100.to_money)
        }.to change {
          contest.reload.win_bet_pool
        }.from(Money.zero).to(100.to_money)
      end
    end

    context "when changing a pending wager's status" do
      it "does not add to the pool when rejected" do
        expect {
          wager = create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :pending, contest: contest, amount: 100.to_money)
          wager.update_attributes(status: :rejected)
        }.to_not change {
          contest.reload.win_bet_pool
        }
      end
      it "does add to the pool when loss" do
        expect {
          wager = create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :pending, contest: contest, amount: 100.to_money)
          wager.update_attributes(status: :loss)
        }.to change {
          contest.reload.win_bet_pool
        }.from(Money.zero).to(100.to_money)
      end
      it "does add to the pool when approved" do
        expect {
          wager = create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :pending, contest: contest, amount: 100.to_money)
          wager.update_attributes(status: :approved)
        }.to change {
          contest.reload.win_bet_pool
        }.from(Money.zero).to(100.to_money)
      end
      it "does add to the pool when win" do
        expect {
          wager = create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :pending, contest: contest, amount: 100.to_money)
          wager.update_attributes(status: :win)
        }.to change {
          contest.reload.win_bet_pool
        }.from(Money.zero).to(100.to_money)
      end
    end
end
```

#### RSpec Output

```bash
$ rspec spec/models/wager_spec.rb:187
Run options: include {:locations=>{"./spec/models/wager_spec.rb"=>[187]}}
[rspec-sidekiq] WARNING! Sidekiq will *NOT* process jobs in this environment. See https://github.com/philostler/rspec-sidekiq/wiki/FAQ-&-Troubleshooting
.....FFFF

Failures:

  1) Wager prize pool counter caches when changing a pending wager's status does not add to the pool when rejected
     Failure/Error:
       expect {
         wager = create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :pending, contest: contest, amount: 100.to_money)
         wager.update_attributes(status: :rejected)
       }.to_not change {
         contest.reload.win_bet_pool
       }
     
       expected result not to have changed, but did change from #<Money fractional:0 currency:USD> to #<Money fractional:-10000 currency:USD>
     # ./spec/models/wager_spec.rb:235:in `block (4 levels) in <top (required)>'

  2) Wager prize pool counter caches when changing a pending wager's status does add to the pool when loss
     Failure/Error:
       expect {
         wager = create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :pending, contest: contest, amount: 100.to_money)
         wager.update_attributes(status: :loss)
       }.to change {
         contest.reload.win_bet_pool
       }.from(Money.zero).to(100.to_money)
     
       expected result to have changed from #<Money fractional:0 currency:USD> to #<Money fractional:10000 currency:USD>, but did not change
     # ./spec/models/wager_spec.rb:243:in `block (4 levels) in <top (required)>'

  3) Wager prize pool counter caches when changing a pending wager's status does add to the pool when approved
     Failure/Error:
       expect {
         wager = create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :pending, contest: contest, amount: 100.to_money)
         wager.update_attributes(status: :approved)
       }.to change {
         contest.reload.win_bet_pool
       }.from(Money.zero).to(100.to_money)
     
       expected result to have changed from #<Money fractional:0 currency:USD> to #<Money fractional:10000 currency:USD>, but did not change
     # ./spec/models/wager_spec.rb:251:in `block (4 levels) in <top (required)>'

  4) Wager prize pool counter caches when changing a pending wager's status does add to the pool when win
     Failure/Error:
       expect {
         wager = create(:wager, teams_string: '1/', wager_type: 'win_bet', status: :pending, contest: contest, amount: 100.to_money)
         wager.update_attributes(status: :win)
       }.to change {
         contest.reload.win_bet_pool
       }.from(Money.zero).to(100.to_money)
     
       expected result to have changed from #<Money fractional:0 currency:USD> to #<Money fractional:10000 currency:USD>, but did not change
     # ./spec/models/wager_spec.rb:259:in `block (4 levels) in <top (required)>'

Finished in 0.88463 seconds (files took 7.57 seconds to load)
9 examples, 4 failures

Failed examples:

rspec ./spec/models/wager_spec.rb:234 # Wager prize pool counter caches when changing a pending wager's status does not add to the pool when rejected
rspec ./spec/models/wager_spec.rb:242 # Wager prize pool counter caches when changing a pending wager's status does add to the pool when loss
rspec ./spec/models/wager_spec.rb:250 # Wager prize pool counter caches when changing a pending wager's status does add to the pool when approved
rspec ./spec/models/wager_spec.rb:258 # Wager prize pool counter caches when changing a pending wager's status does add to the pool when win
```

**Comment by danielricecodes** [comment]
@magnusvk - I figured out the issue.  I am not updating the `delta_column` so the counter cache update is not triggered.  This is coded [here](https://github.com/magnusvk/counter_culture/blob/master/lib/counter_culture/extensions.rb#L118).  

I believe I am headed towards forking your gem now!  

Thank you for making this gem by the way - I have used it in numerous projects and it always works perfectly.

**Comment by magnusvk** [comment]
@danielricecodes thanks for the kind words! Sorry this doesn't work out of the box; feel free to fork, of course, but if there's a relatively-contained way of adding optional support for this I'd look at a PR, too.

**Comment by danielricecodes** [comment]
@magnusvk - I've finally been able to return to this issue after some time.  I've been able to determine that my configuration above is actually fine - but I had some additional `after_create` callbacks that were interfering with `counter_culture`.  That said, I haven't been able to completely rule out a potential bug when the counter culture class has other `after_*` callbacks defined.

I've seen some interesting behavior where the `execute_after_commit` block appears to not run and the the `@_counter_culture_active` is set to true when it should be false.  When this happens, the counter cache update block is never executed...

I was able to see this happening using `binding.pry` in my specs, but I don't have a reproducible test case for you (yet).

```ruby
  def _wrap_in_counter_culture_active(&block)
      if @_counter_culture_active
        # don't do anything; we are already active for this transaction
      else
        @_counter_culture_active = true
        block.call
        ### I THINK THERE MAY BE A BUG HERE WHEN THERE ARE OTHER CALLBACKS DEFINED ON THE SAME MODEL.
        execute_after_commit { @_counter_culture_active = false}
      end
    end
```

**Comment by magnusvk** [comment]
If that's the case, [upgrading to 2.0.0](https://github.com/magnusvk/counter_culture/blob/master/CHANGELOG.md#200-june-12-2018) might fix this for you. That removes the whole `@_counter_culture_active` and `execute_after_commit` logic.
