### ISSUE TITLE
Calling counter_culture_fix_counts throws ArgumentError

### ISSUE THREAD

**Issue by pcraston** [magnusvk/counter_culture#197]
Sorry if I'm missing something obvious here but I'm getting a `ArgumentError: wrong number of arguments (given 0, expected 1..3)` error when I run the `counter_culture_fix_counts` command without any arguments (as shown in the readme) on my model.

Here's the traceback:

```
ArgumentError: wrong number of arguments (given 0, expected 1..3)
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/httparty-0.14.0/lib/httparty.rb:69:in `logger'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/relation/delegation.rb:94:in `public_send'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/relation/delegation.rb:94:in `block in method_missing'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/relation.rb:302:in `scoping'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/relation/delegation.rb:94:in `method_missing'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.7/lib/active_record/relation/batches.rb:112:in `find_in_batches'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/counter_culture-1.8.1/lib/counter_culture/reconciler.rb:100:in `block in perform'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/counter_culture-1.8.1/lib/counter_culture/reconciler.rb:79:in `each'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/counter_culture-1.8.1/lib/counter_culture/reconciler.rb:79:in `perform'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/counter_culture-1.8.1/lib/counter_culture/reconciler.rb:32:in `block in reconcile!'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/counter_culture-1.8.1/lib/counter_culture/reconciler.rb:31:in `each'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/counter_culture-1.8.1/lib/counter_culture/reconciler.rb:31:in `reconcile!'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/counter_culture-1.8.1/lib/counter_culture/extensions.rb:67:in `block in counter_culture_fix_counts'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/counter_culture-1.8.1/lib/counter_culture/extensions.rb:62:in `each'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/counter_culture-1.8.1/lib/counter_culture/extensions.rb:62:in `flat_map'
from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/counter_culture-1.8.1/lib/counter_culture/extensions.rb:62:in `counter_culture_fix_counts'
```

Might be related to https://github.com/magnusvk/counter_culture/issues/196 ?

**Comment by pcraston** [comment]
Seems like it's an issue with the model in my project. sorry for the noise..
