### ISSUE TITLE
Using Rails 6.0.0-rc, CI failed.

### ISSUE THREAD

**Issue by soranoba** [magnusvk/counter_culture#267]
https://travis-ci.org/soranoba/counter_culture/builds/573060376

```
  1) CounterCulture increments counter cache on create
     Failure/Error: timestamp_columns << touch if touch != true
     
     FrozenError:
       can't modify frozen Array
     # ./lib/counter_culture/counter.rb:72:in `change_counter_cache'
     # ./lib/counter_culture/extensions.rb:96:in `block in _update_counts_after_create'
     # ./lib/counter_culture/extensions.rb:94:in `each'
     # ./lib/counter_culture/extensions.rb:94:in `_update_counts_after_create'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:429:in `block in make_lambda'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:239:in `block in halting_and_conditional'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:518:in `block in invoke_after'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:518:in `each'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:518:in `invoke_after'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:136:in `run_callbacks'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:827:in `_run_create_callbacks'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/callbacks.rb:332:in `_create_record'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/timestamp.rb:111:in `_create_record'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/persistence.rb:906:in `create_or_update'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/callbacks.rb:328:in `block in create_or_update'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:135:in `run_callbacks'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/callbacks.rb:328:in `create_or_update'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/timestamp.rb:129:in `create_or_update'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/persistence.rb:470:in `save'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/validations.rb:47:in `save'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/transactions.rb:315:in `block in save'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:275:in `transaction'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/transactions.rb:212:in `transaction'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/transactions.rb:315:in `save'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/suppressor.rb:44:in `save'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/collection_association.rb:362:in `insert_record'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/has_many_association.rb:36:in `insert_record'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/collection_association.rb:347:in `block (2 levels) in _create_record'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/collection_association.rb:443:in `replace_on_target'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/collection_association.rb:285:in `add_to_target'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/collection_association.rb:346:in `block in _create_record'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/collection_association.rb:135:in `block in transaction'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:277:in `block in transaction'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:277:in `transaction'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/transactions.rb:212:in `transaction'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/collection_association.rb:134:in `transaction'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/collection_association.rb:344:in `_create_record'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/has_many_association.rb:116:in `_create_record'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/association.rb:191:in `create'
     # /home/travis/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.0/lib/active_record/associations/collection_proxy.rb:347:in `create'
     # ./spec/counter_culture_spec.rb:77:in `block (2 levels) in <top (required)>'
```

**Comment by magnusvk** [comment]
Thanks for reporting this, #268 should fix this. 🤞
